### ISSUE TITLE
some questions on t_c, x_t_tilde

### ISSUE THREAD

**Issue by cxw-droid** [jinhaoduan/SecMI#2]
Hi, thank you for your paper and for sharing the code. May I ask some questions?

1)
https://github.com/jinhaoduan/SecMI/blob/25603502f524108bb08c2dd5e4002993ac35589a/mia_evals/secmia.py#L36
 When you calculate `epsilon`, initially `t_c` is `0`, but during DDPM inference, time step `t_c` should be equal or great than `1`. So can we set `t_c` to 0 here?

2) In Equation (13) in the paper, the $\tilde{x\_t}$ is calculated many steps iteratively. Can we just calculate $\tilde{x\_t}$ based on Equation (4) in one step?

Thanks.

**Comment by jinhaoduan** [comment]
Thanks for your interest.

1. `t_c` is initialized as 0 at first and it will be assigned to `k`, `2k`, `3k`, ..., `t_SEC` during the reverse process, e.g., 10, 20, 30, ..., in our case. Therefore we can't set `t_c` to be a fixed 0 here.
2. We can't do that because Equation (13) is calculated based on deterministic reversing and denoising, while Equation (4) is the non-deterministic diffusion process. I assume you would like to know whether we could use Equation (9) to achieve "one-step" reverse and denoising. In this way, we can but that will lead to an attack performance drop.

**Comment by cxw-droid** [comment]
Thank you very much for the reply.

Yes, `t_c` is not fixed, but initially can we set it to `0`? because in the DDPM paper, `t_c`$\ge 1$. So `t_c=0` seems out of range?

Also $x_0$ is a deterministic value, and if we initially use `t_c = 0` and $x_0$ as `model` input, we will get an `epsilon` for $x_0$

**Comment by jinhaoduan** [comment]
1. In most implementations (also in our codebase), `t_c` is set to [0, 999] (https://github.com/w86763777/pytorch-ddpm/blob/be2787b7417885292a2ba8dd970e981310e0acc3/diffusion.py#L37C1-L37C1) and it will be initialized to 0.
2. Deterministic `epsilon` doesn't mean the reversing/denoising process is deterministic. To get `x_1`, we need to update `x_0` in a deterministic manner (Equation 9).

**Comment by cxw-droid** [comment]
1. My understanding is that `t_c` set to `[0, 999]` in the code corresponds to `[1, 1000]` in the DDPM paper. 

https://github.com/w86763777/pytorch-ddpm/blob/be2787b7417885292a2ba8dd970e981310e0acc3/diffusion.py#L23
In the above code, `beta_1` corresponds to the parameter for $x_1$. 

https://github.com/jinhaoduan/SecMI/blob/25603502f524108bb08c2dd5e4002993ac35589a/mia_evals/secmia.py#L38
but here in the above code, when initially `t_c=0`, the input `x` is the initial clean image `x_0`, and thus the code gets a predicted `pred_x_0` from a clean image `x_0`. So I was confused.

2. The Eq. 9 in the paper uses an $\epsilon_\theta(x_t, t)$. Based on Eq. (4) and DDPM paper, any value can be use since it is a diffusion process. So here it seems not quite clear why an inferred value $\epsilon_\theta(x_t, t)$ is used.

**Comment by zhaisf** [comment]
> 1. My understanding is that `t_c` set to `[0, 999]` in the code corresponds to `[1, 1000]` in the DDPM paper.

I agree. 

During the reverse process of DDIM (refer to Eq. (10) in the [DDIM paper](https://arxiv.org/abs/2010.02502) ), t cannot be 0. 
This code actually confuses t_0 and t_1, leading to the use of the alpha parameter of the t+1 timestep for all t timesteps. 

However, since these two are very similar, the results do not show significant errors.

**Comment by jinhaoduan** [comment]
Oh, now I understand the question raised by @cxw-droid . I was kind of confused before. I agree that t=0 is meaningless for DDIM. We will fix this. Thank you so much for pointing out this.
